const { version } = require('../../package.json');
const config = require('../config');

function render(context) {
    header(context);
    toc(context);
    // details(context);

    footer(context);
}

function header({ stream }) {
    const title = config.title;
    stream.write(`# ${title}\n`);
}

function toc({ stream, tables }) {
    let i = 1;
    const names = Object.keys(tables).sort();
    stream.write('## Tables \n');
    tocHeader(stream);
    names.forEach(name => {
        stream.write(`|${i}| [${name}](#${name}) |`);
        if (!config.noDescriptions) {
            stream.write(` ${tables[name].description} |`);
        }
        stream.write('\n');
        i++;
    });
}

function tocHeader(stream) {
    if (config.noDescriptions) {
        stream.write('|\# |Table Name|\n|--:|----------|\n');
    } else {
        stream.write('|\# |Table Name| Description|\n|--:|----------|------------|\n');
    }
}

function details({ stream, tables }) {
    stream.write('## Details \n');
    for (let table in tables) {
        stream.write(`### ${table}\n`);
        if (config.noDescriptions) {
            stream.write('|\# |column|type|nullable|default|constraints|\n');
            stream.write('|--:|------|----|--------|-------|-----------|\n');
        } else {
            stream.write(`${tables[table].description}\n\n`);
            stream.write('|\# |column|type|nullable|default|constraints|description|\n');
            stream.write('|--:|------|----|--------|-------|-----------|-----------|\n');
        }
        columnDetails({ stream, columns: tables[table].columns});
    }
}

function columnDetails({ stream, columns }) {
    let i = 1;
    for (let name in columns) {
        const data = columns[name];
        stream.write(`| ${i} | ${name} |  ${data.type} | ${data.nullable} | ${mdEsc(data.default)} | ${constraintDetails(data.constraints)} |`);
        if (!config.noDescriptions) {
            stream.write(` ${mdEsc(data.description)} |`);
        }
        stream.write('\n');
        i++;
    }
}

function constraintDetails(constraints) {
    if (!constraints) {
        return '';
    }
    let constraintData = [];
    if (constraints) {
        if (constraints.pk) {
            constraintData.push('**PK**');
        }
        if (constraints.unq) {
            constraintData.push('**UNIQ**');
        }
        if (constraints.fk) {
            constraintData.push(`**FK** \([${constraints.fk.table}.${constraints.fk.column}](#${constraints.fk.table})\)`);
        }
    }
    return constraintData.join(', ');
}

function mdEsc(str) {
    if (!str) {
        return '';
    }
    return str.replace(/\|/g, '\\$&');
}

function footer({ stream }) {
    stream.write('---\n');
    stream.write(`generated by [pg-doc](https://github.com/echetzakis/pg-doc) v${version}\n`);
    stream.end();
}

module.exports = render;
