const { version } = require('../package.json');
const config = require('./config');

function writeDoc(context) {
    header(context);
    toc(context);
    details(context);
    footer(context);
}

function header({ stream }) {
    const title = config.title;
    stream.write(`# ${title}\n`);
}

function toc({ stream, tables }) {
    if (!config.toc) {
        return;
    }
    let i = 1;
    const names = Object.keys(tables).sort();
    let initial = names[0][0].toUpperCase();
    const splitByInitial = config.splitByInitial && names.length > config.splitLimit;
    stream.write('## Tables \n');
    if (splitByInitial) {
        navBar(stream, names);
    }
    tocHeader(stream, splitByInitial, initial);
    names.forEach(name => {
        let newInitial = name[0].toUpperCase();
        if (splitByInitial && initial !== newInitial) {
            initial = newInitial;
            tocHeader(stream, splitByInitial, initial);
        }
        stream.write(`|${i}| [${name}](#${name}) |`);
        if (!config.noDescriptions) {
            stream.write(` ${tables[name].description} |`);
        }
        stream.write('\n');
        i++;
    });
}

function navBar(stream, names) {
    stream.write(names.map(name => name[0].toUpperCase()).reduce((initials, letter) => {
        if (!initials.includes(letter)) {
            initials.push(letter);
        }
        return initials;
    }, []).map(initial => `[${initial}](#${initial})`).join(' \\| '));
    stream.write('\n');
}

function tocHeader(stream, splitByInitial, initial) {
    if (splitByInitial) {
        stream.write(`### ${initial} \n`);
    }
    if (config.noDescriptions) {
        stream.write('|\# |Table Name|\n|--:|----------|\n');
    } else {
        stream.write('|\# |Table Name| Description|\n|--:|----------|------------|\n');
    }
}

function details({ stream, tables, columns, constraints }) {
    stream.write('## Details \n');
    for (let table in tables) {
        stream.write(`### ${table}\n`);
        if (config.noDescriptions) {
            stream.write('|\# |column|type|nullable|default|constraints|\n');
            stream.write('|--:|------|----|--------|-------|-----------|\n');
        } else {
            stream.write(`${tables[table].description}\n\n`);
            stream.write('|\# |column|type|nullable|default|constraints|description|\n');
            stream.write('|--:|------|----|--------|-------|-----------|-----------|\n');
        }
        columnDetails({ stream, columns: columns[table] || {}, constraints: constraints[table] || {} });
    }
}

function columnDetails({ stream, columns, constraints }) {
    let i = 1;
    for (let name in columns) {
        const data = columns[name];
        stream.write(`| ${i} | ${name} |  ${data.type} | ${data.nullable} | ${mdEsc(data.default)} | ${constraintDetails(constraints[name])} |`);
        if (!config.noDescriptions) {
            stream.write(` ${mdEsc(data.description)} |`);
        }
        stream.write('\n');
        i++;
    }
}

function constraintDetails(constraints) {
    if (!constraints) {
        return '';
    }
    let constraintData = [];
    if (constraints) {
        if (constraints.pk) {
            constraintData.push('**PK**');
        }
        if (constraints.unq) {
            constraintData.push('**UNIQ**');
        }
        if (constraints.fk) {
            constraintData.push(`**FK** \([${constraints.fk.table}.${constraints.fk.column}](#${constraints.fk.table})\)`);
        }
    }
    return constraintData.join(', ');
}

function mdEsc(str) {
    if (!str) {
        return '';
    }
    return str.replace(/\|/g, '\\$&');
}

function footer({ stream }) {
    stream.write('---\n');
    stream.write(`generated by [pg-doc](https://github.com/echetzakis/pg-doc) v${version}\n`);
    stream.end();
}

module.exports = writeDoc;
